/*
 * data.ts — CONTENU des schémas de flux (le seul fichier à éditer pour ajouter/mettre à jour un cas).
 * Ne pas toucher au style (flowSchemas.css) ni au moteur (flowchart.ts) : une nouveauté réutilise le style à l'identique.
 *
 *  STORE    : publicStoreId d'exemple (placeholder d'affichage dans les payloads).
 *  P        : payloads exacts, indexés par clé (référencés par les nœuds cliquables via `pay("<clé>", ...)`).
 *  FAMILIES : familles d'opérations. Chaque schéma :
 *    { h:titre, axes:[[label,'on'|'acc'|''],...], why:"2-3 phrases", d:"<mini-flowchart>", warn?, info? }
 *    `d` = sous-ensemble de la syntaxe mermaid `flowchart LR` interprété par app.js :
 *      - `A["Libellé"] --> B["Autre"]`   (nœud rectangle ; `<br/>` pour 2 lignes)
 *      - `X{"Décision ?"}`               (losange pointillé)
 *      - `... -->|label| ...`            (libellé d'arête)
 *      - `N["..."]:::call`               (nœud CORAL = appel API cliquable)
 *      - `click N call pay("<clé P>","POST|GET|DELETE","/chemin")`  (payload ouvert au clic)
 */
import type { Family } from './types';

export const STORE = '547c…';
export const payloads: Record<string, string> = {
  amtUp15:'{\n  "amount": { "value": 15000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'"\n}',
  amt12:'{\n  "amount": { "value": 12000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'"\n}',
  amtDown7:'{\n  "amount": { "value": 7000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'"\n}',
  compl5:'{\n  "amount": { "value": 5000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'",\n  "token": "<token stocké>",\n  "shopperReference": "client-42",\n  "recurringModel": "UNSCHEDULED",\n  "reference": "CMD-1-complement"\n}',
  compl2:'{\n  "amount": { "value": 2000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'",\n  "token": "<token>",\n  "shopperReference": "client-42",\n  "recurringModel": "UNSCHEDULED",\n  "reference": "CMD-1-complement"\n}',
  cap40:'{\n  "amount": { "value": 4000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'"\n}',
  capTotal:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'",\n  "reference": "CAP-1"\n}',
  reauth6:'{\n  "amount": { "value": 6000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'",\n  "token": "<token>",\n  "shopperReference": "client-42",\n  "recurringModel": "UNSCHEDULED",\n  "reference": "CMD-1-b"\n}',
  reste6:'{\n  "amount": { "value": 6000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'",\n  "token": "<token>",\n  "shopperReference": "client-42",\n  "recurringModel": "UNSCHEDULED",\n  "reference": "CMD-1-reste"\n}',
  extend:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'",\n  "reason": "DELAYED_CHARGE"\n}',
  reauth10:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'",\n  "token": "<token>",\n  "shopperReference": "client-42",\n  "recurringModel": "UNSCHEDULED",\n  "reference": "CMD-1-reauth"\n}',
  cancel:'{\n  "publicStoreId": "'+STORE+'"\n}',
  refundTotal:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'"\n}',
  refund30:'{\n  "amount": { "value": 3000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'"\n}',
  tokenise:'{\n  "amount": { "value": 0, "currency": "EUR" },\n  "reference": "TOKENISE-1",\n  "publicStoreId": "'+STORE+'",\n  "returnUrl": "https://ton-pms/retour",\n  "capture": { "mode": "MANUAL" },\n  "tokenization": { "shopperReference": "client-42", "recurringModel": "CARD_ON_FILE" }\n}',
  mit10:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "publicStoreId": "'+STORE+'",\n  "token": "<token>",\n  "shopperReference": "client-42",\n  "recurringModel": "UNSCHEDULED",\n  "reference": "MIT-1"\n}',
  motoTok0:'{\n  "amount": { "value": 0, "currency": "EUR" },\n  "reference": "TOKENISE-MOTO-1",\n  "publicStoreId": "'+STORE+'",\n  "returnUrl": "https://ton-pms/retour",\n  "capture": { "mode": "MANUAL" },\n  "tokenization": { "shopperReference": "client-42", "recurringModel": "CARD_ON_FILE" },\n  "moto": true\n}',
  session:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "reference": "CMD-1",\n  "publicStoreId": "'+STORE+'",\n  "returnUrl": "https://ton-pms/retour",\n  "capture": { "mode": "IMMEDIATE" }\n}',
  sessionManual:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "reference": "CMD-1",\n  "publicStoreId": "'+STORE+'",\n  "returnUrl": "https://ton-pms/retour",\n  "capture": { "mode": "MANUAL" }\n}',
  sessionPreauth:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "reference": "CMD-1",\n  "publicStoreId": "'+STORE+'",\n  "returnUrl": "https://ton-pms/retour",\n  "preAuth": true,\n  "capture": { "mode": "MANUAL" }\n}',
  posPay:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "deviceId": "V400m-123456789",\n  "saleReference": "sale-2026-000789",\n  "publicStoreId": "'+STORE+'",\n  "preAuth": false\n}',
  posPreauth:'{\n  "amount": { "value": 10000, "currency": "EUR" },\n  "deviceId": "V400m-123456789",\n  "saleReference": "sale-2026-000789",\n  "publicStoreId": "'+STORE+'",\n  "preAuth": true\n}'
};

/*
 * webhooks — corps des notifications que le PMS reçoit (structure Adyen : le webhook-service enregistre le
 * rawPayload Adyen, notification-service le transmet). Cliquable sur les cases vertes (nœud :::hook + click wh()).
 */
export const webhooks: Record<string, string> = {
  whAuth:'{\n  "live": "false",\n  "notificationItems": [\n    {\n      "NotificationRequestItem": {\n        "eventCode": "AUTHORISATION",\n        "success": "true",\n        "pspReference": "8836183819713706",\n        "merchantAccountCode": "SEPTEO_ECOM",\n        "merchantReference": "CMD-1",\n        "amount": { "currency": "EUR", "value": 10000 },\n        "paymentMethod": "visa",\n        "eventDate": "2026-09-23T10:00:00+02:00",\n        "additionalData": { "store": "ST3ABCD1234567890" }\n      }\n    }\n  ]\n}',
  whCapture:'{\n  "live": "false",\n  "notificationItems": [\n    {\n      "NotificationRequestItem": {\n        "eventCode": "CAPTURE",\n        "success": "true",\n        "pspReference": "9914694372892123",\n        "originalReference": "8836183819713706",\n        "merchantAccountCode": "SEPTEO_ECOM",\n        "merchantReference": "CMD-1",\n        "amount": { "currency": "EUR", "value": 10000 },\n        "eventDate": "2026-09-23T10:05:00+02:00"\n      }\n    }\n  ]\n}',
  whToken:'{\n  "live": "false",\n  "notificationItems": [\n    {\n      "NotificationRequestItem": {\n        "eventCode": "AUTHORISATION",\n        "success": "true",\n        "pspReference": "8836183819799999",\n        "merchantAccountCode": "SEPTEO_ECOM",\n        "merchantReference": "TOKENISE-1",\n        "amount": { "currency": "EUR", "value": 0 },\n        "eventDate": "2026-09-23T09:40:00+02:00",\n        "additionalData": {\n          "recurring.recurringDetailReference": "8415718415718415",\n          "recurring.shopperReference": "client-42"\n        }\n      }\n    }\n  ]\n}',
  whOrderClosed:'{\n  "live": "false",\n  "notificationItems": [\n    {\n      "NotificationRequestItem": {\n        "eventCode": "ORDER_CLOSED",\n        "success": "true",\n        "pspReference": "883612345678ORDR",\n        "merchantAccountCode": "SEPTEO_ECOM",\n        "merchantReference": "CMD-ORDER-1",\n        "amount": { "currency": "EUR", "value": 10000 },\n        "eventDate": "2026-09-23T11:00:00+02:00",\n        "additionalData": {\n          "order-1-pspReference": "8836000000000CB1",\n          "order-1-paymentMethod": "visa",\n          "order-2-pspReference": "8836000000000ANCV",\n          "order-2-paymentMethod": "ancv"\n        }\n      }\n    }\n  ]\n}',
  whPosAuth:'{\n  "live": "false",\n  "notificationItems": [\n    {\n      "NotificationRequestItem": {\n        "eventCode": "AUTHORISATION",\n        "success": "true",\n        "pspReference": "8836183819788888",\n        "merchantAccountCode": "SEPTEO_POS",\n        "merchantReference": "sale-2026-000789",\n        "amount": { "currency": "EUR", "value": 10000 },\n        "paymentMethod": "mc",\n        "eventDate": "2026-09-23T14:00:00+02:00",\n        "additionalData": { "POIID": "V400m-123456789" }\n      }\n    }\n  ]\n}'
};

export const families: Family[] = [
 {tag:'CAS',title:'Enregistrer une carte par téléphone (MOTO), puis débiter plus tard',flow:'MOTO → ContAuth',lead:"Le client donne sa carte par téléphone. Tu l'enregistres sans le débiter, et tu débites toi-même le moment venu (client absent). Deux temps : d'abord la session à 0 €, plus tard le paiement sur le token.",schemas:[
   {h:'Étape 1 puis 2 · de bout en bout',axes:[['montant 0','on'],['MOTO','on'],['token','on'],['ContAuth','on']],
    why:"<b>Étape 1</b> — tu ouvres une session à 0 € en MOTO avec tokenisation : l'agent saisit la carte du client, rien n'est débité, et la <b>carte enregistrée (token)</b> te revient par <b>webhook</b>. <b>Étape 2</b>, quand tu veux — un jour, un mois plus tard — tu lances un paiement sur ce token en <b>ContAuth</b> : c'est toi qui déclenches, le client n'est pas là.",
    d:'flowchart LR\n S["POST /sessions<br/>0 € · MOTO · token"]:::call --> DI["Agent saisit la carte<br/>(Drop-in MOTO)"]:::client\n DI --> WH1["webhook AUTHORISATION<br/>token reçu"]:::hook\n WH1 --> OK1["Carte enregistrée<br/>rien débité"]\n OK1 --> P["POST /payments<br/>token · ContAuth"]:::call\n P --> WH2["webhook AUTHORISATION<br/>paiement confirmé"]:::hook\n WH2 --> OK2["Argent débité"]\n click S call pay("motoTok0","POST","/sessions")\n click P call pay("mit10","POST","/payments")\n click WH1 wh("whToken")\n click WH2 wh("whAuth")',
    warn:"Un MOTO sert <b>uniquement</b> à tokeniser : la session doit être à <b>0 €</b>, en capture <b>MANUAL</b>, avec une <b>tokenisation</b>. Toute autre combinaison est refusée en <b>422 MOTO_NOT_CAPTURABLE</b> — un paiement MOTO ne doit jamais être capturé (le token servira au débit ultérieur en ContAuth).",
    info:"<b>Code couleur</b> — <span style=\"color:var(--send-ink)\">coral</span> : <b>tu appelles l'API</b> · <span style=\"color:var(--accent)\">bleu</span> : <b>côté client</b> · <span style=\"color:var(--ok)\">vert</span> : <b>événement reçu</b> (webhook). <code class='inl'>ContAuth</code> (aussi appelé <b>MIT</b>) = paiement que <b>tu</b> déclenches, client absent. Le <b>token</b> = la carte enregistrée, jamais le numéro."}
 ]},
 {tag:'#2739',title:'Ajustement du montant',flow:'ECOM',lead:'Changer le montant autorisé (avant/pendant la capture) sur une pré-autorisation.',schemas:[
   {h:'Avec token · sans capture',axes:[['preAuth:true','on'],['MANUAL','on'],['token','on']],
    why:"Tu as pré-autorisé un montant et gardé un token. Tu peux le monter ou le baisser avant capture. Si Adyen refuse une hausse, le token te sauve : tu ré-autorises juste le complément à part.",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> H{"Sens ?"}\n H -->|hausse| B["POST /amount<br/>hausse"]:::call\n B --> U{"Adyen accepte ?"}\n U -->|OK| U1["Montant augmenté"]\n U -->|KO| C["POST /payments<br/>complément"]:::call\n C --> C1["Auth + complément"]\n H -->|baisse| D["POST /amount<br/>baisse"]:::call\n D --> D1["Montant diminué"]\n click B call pay("amtUp15","POST","/payments/{ref}/amount")\n click C call pay("compl5","POST","/payments")\n click D call pay("amtDown7","POST","/payments/{ref}/amount")'},
   {h:'Sans token · sans capture',axes:[['preAuth:true','on'],['MANUAL','on'],['sans token','']],
    why:"Même principe, mais sans filet : sans token, si Adyen refuse la hausse tu ne peux pas rattraper le complément. Le montant initial reste, point.",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> B["POST /amount"]:::call\n B --> U{"Adyen accepte ?"}\n U -->|OK| U1["Montant modifié"]\n U -->|KO| U2["Montant initial conservé"]\n click B call pay("amtUp15","POST","/payments/{ref}/amount")',
    warn:"Pour couvrir le refus de hausse, ouvre la session <b>avec token</b>."},
   {h:'Avec token · avec capture · capture multiple ON',axes:[['preAuth:true','on'],['MANUAL','on'],['token','on'],['multi-capture ON','acc']],
    why:"Tu encaisses en plusieurs fois ET tu peux encore ajuster : la capture multiple garde l'autorisation ouverte après une capture partielle ; le token sert de repli si une hausse est refusée.",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> P["POST /captures<br/>partielle"]:::call\n P --> B["POST /amount"]:::call\n B --> U{"Adyen accepte ?"}\n U -->|OK| U1["Montant augmenté"]\n U -->|KO| C["POST /payments<br/>complément"]:::call\n C --> C1["Auth + complément"]\n click P call pay("cap40","POST","/payments/{ref}/captures")\n click B call pay("amt12","POST","/payments/{ref}/amount")\n click C call pay("compl5","POST","/payments")'},
   {h:'Avec/sans token · avec capture · capture multiple OFF',axes:[['preAuth:true','on'],['MANUAL','on'],['multi-capture OFF','acc']],
    why:"Piège : sans capture multiple, une capture partielle CLÔTURE l'autorisation. Plus d'ajustement possible. La seule suite, c'est ré-autoriser sur le token (il faut donc un token).",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> P["POST /captures<br/>partielle"]:::call\n P --> X["Autorisation<br/>clôturée"]\n X --> R["POST /payments<br/>nouvelle pré-auth"]:::call\n click P call pay("cap40","POST","/payments/{ref}/captures")\n click R call pay("reauth6","POST","/payments")',
    warn:"Sans token ici, le reste est perdu (ni 2ᵉ capture, ni ré-auth)."},
   {h:'Sans token · avec capture · capture multiple ON',axes:[['preAuth:true','on'],['MANUAL','on'],['sans token',''],['multi-capture ON','acc']],
    why:"Comme le cas token + multi-capture, mais sans repli : tu peux capturer partiellement puis ajuster, sauf qu'une hausse refusée reste sans solution (pas de complément sans token).",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> P["POST /captures<br/>partielle"]:::call\n P --> B["POST /amount"]:::call\n B --> U{"Adyen accepte ?"}\n U -->|OK| U1["Montant augmenté"]\n U -->|KO| U2["Montant initial conservé"]\n click P call pay("cap40","POST","/payments/{ref}/captures")\n click B call pay("amt12","POST","/payments/{ref}/amount")'}
 ]},
 {tag:'#2740',title:'Prolongation de validité',flow:'ECOM',lead:"Étendre la durée d'une autorisation (caution), montant inchangé. Appel /extend avec un reason.",schemas:[
   {h:'Avec token · sans capture',axes:[['preAuth:true','on'],['MANUAL','on'],['token','on']],
    why:"Ta caution va expirer et tu veux la garder valide plus longtemps, sans changer le montant. Si Adyen refuse (ou si c'est déjà expiré), tu repars sur une (nouvelle) autorisation via le token.",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> E["POST /extend"]:::call\n E --> R{"Adyen accepte ?"}\n R -->|OK| OK["Durée prolongée"]\n R -->|KO / expirée| S["POST /payments<br/>auth sur token"]:::call\n S --> S1["Nouvelle auth"]\n click E call pay("extend","POST","/payments/{ref}/extend")\n click S call pay("reauth10","POST","/payments")',
    info:"<code class='inl'>reason</code> possibles : <code class='inl'>DELAYED_CHARGE</code>, <code class='inl'>NO_SHOW</code>, <code class='inl'>INSTALLMENT</code>."},
   {h:'Sans token · sans capture',axes:[['preAuth:true','on'],['MANUAL','on'],['sans token','']],
    why:"Pareil, mais sans token pas de repli : si la prolongation est refusée, la durée initiale reste et tu ne peux pas ré-autoriser.",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> E["POST /extend"]:::call\n E --> R{"Adyen accepte ?"}\n R -->|OK| OK["Durée prolongée"]\n R -->|KO| K["Durée initiale conservée"]\n click E call pay("extend","POST","/payments/{ref}/extend")'},
   {h:'Avec token · avec capture · capture multiple ON',axes:[['preAuth:true','on'],['MANUAL','on'],['token','on'],['multi-capture ON','acc']],
    why:"Tu as déjà capturé une partie et tu prolonges le reste de la caution. Repli sur token si le extend est refusé.",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> P["POST /captures<br/>partielle"]:::call\n P --> E["POST /extend"]:::call\n E --> R{"Adyen accepte ?"}\n R -->|OK| OK["Nouvelle validité"]\n R -->|KO| S["POST /payments<br/>2e auth"]:::call\n S --> Sa["Auth + nouvelle"]\n click P call pay("cap40","POST","/payments/{ref}/captures")\n click E call pay("extend","POST","/payments/{ref}/extend")\n click S call pay("reauth10","POST","/payments")'},
   {h:'Avec/sans token · avec capture · capture multiple OFF',axes:[['preAuth:true','on'],['MANUAL','on'],['multi-capture OFF','acc']],
    why:"Même piège que l'ajustement : la capture partielle clôture l'autorisation, donc plus de prolongation. Seule suite : ré-autoriser sur le token.",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> P["POST /captures<br/>partielle"]:::call\n P --> X["Clôturée"]\n X --> R["POST /payments<br/>nouvelle pré-auth"]:::call\n click P call pay("cap40","POST","/payments/{ref}/captures")\n click R call pay("reauth10","POST","/payments")'},
   {h:'Sans token · avec capture · capture multiple ON',axes:[['preAuth:true','on'],['MANUAL','on'],['sans token',''],['multi-capture ON','acc']],
    why:"Comme le cas token + multi-capture, mais sans repli : tu captures une partie puis tu prolonges le reste ; si le extend est refusé, la durée initiale reste et tu ne peux pas ré-autoriser (pas de token).",
    d:'flowchart LR\n q0["POST /sessions<br/>preAuth + MANUAL"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Auth pré-aut"]\n click q0 call pay("sessionPreauth","POST","/sessions")\n click q2 wh("whAuth")\n A["Auth pré-aut"] --> P["POST /captures<br/>partielle"]:::call\n P --> E["POST /extend"]:::call\n E --> R{"Adyen accepte ?"}\n R -->|OK| OK["Nouvelle validité"]\n R -->|KO| K["Durée initiale conservée"]\n click P call pay("cap40","POST","/payments/{ref}/captures")\n click E call pay("extend","POST","/payments/{ref}/extend")',
    warn:"Sans token, un extend refusé est sans recours (pas de ré-auth)."}
 ]},
 {tag:'#2565',title:'Capture totale',flow:'ECOM',lead:"Encaisser l'intégralité. Vaut pour la pré-aut comme la finale (seule l'ouverture de session change) — à une nuance près : sur une autorisation finale, l'ajustement /amount n'existe pas, un dépassement passe directement par une ré-autorisation sur token (ou est impossible sans token).",schemas:[
   {h:'Avec token',axes:[['MANUAL','on'],['token','on']],
    why:"Tu encaisses tout d'un coup. Si le montant à encaisser dépasse l'autorisé, tu ajustes à la hausse ; et si Adyen refuse la hausse, le token permet d'autoriser le manquant à part.",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Autorisation"]\n click q0 call pay("sessionManual","POST","/sessions")\n click q2 wh("whAuth")\n A["Autorisation"] --> C["POST /captures<br/>totale"]:::call\n C --> M{"Montant vs autorisé"}\n M -->|exact| T["Capture totale"]\n M -->|supérieur| ADJ["POST /amount<br/>hausse"]:::call\n ADJ -->|OK| T2["Capture du nouveau montant"]\n ADJ -->|KO| RE["POST /payments<br/>complément"]:::call\n RE --> T3["Capture + 2e auth"]\n click C call pay("capTotal","POST","/payments/{ref}/captures")\n click ADJ call pay("amt12","POST","/payments/{ref}/amount")\n click RE call pay("compl2","POST","/payments")',
    info:"Ce schéma vaut pour une <b>pré-autorisation</b>. Sur une <b>autorisation finale</b>, l'ajustement <code class='inl'>/amount</code> n'est pas disponible : un dépassement passe directement par une <b>ré-autorisation sur token</b> (ou est impossible sans token)."},
   {h:'Sans token',axes:[['MANUAL','on'],['sans token','']],
    why:"Capture totale simple. Mais si l'encaissement dépasse l'autorisé et qu'Adyen refuse la hausse, impossible d'aller au-delà (pas de complément sans token).",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Autorisation"]\n click q0 call pay("sessionManual","POST","/sessions")\n click q2 wh("whAuth")\n A["Autorisation"] --> C["POST /captures<br/>totale"]:::call\n C --> M{"Montant vs autorisé"}\n M -->|exact| T["Capture totale"]\n M -->|supérieur| ADJ["POST /amount<br/>hausse"]:::call\n ADJ -->|OK| T2["Capture du nouveau montant"]\n ADJ -->|KO| X["Au-delà impossible<br/>sans token"]\n click C call pay("capTotal","POST","/payments/{ref}/captures")\n click ADJ call pay("amt12","POST","/payments/{ref}/amount")',
    warn:"Pour dépasser l'autorisé en cas de refus, ouvre la session <b>avec token</b>."}
 ]},
 {tag:'#2565',title:'Capture partielle',flow:'ECOM',lead:'Encaisser en plusieurs fois. Le nombre de captures dépend du réglage capture multiple du compte.',schemas:[
   {h:'Avec/sans token · capture multiple ON',axes:[['MANUAL','on'],['multi-capture ON','acc']],
    why:"Tu encaisses par tranches tant que la somme reste ≤ l'autorisé. Quand tu as fini, tu clôtures le solde non capturé (sinon il se clôt seul quand la somme atteint l'autorisé).",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Autorisation"]\n click q0 call pay("sessionManual","POST","/sessions")\n click q2 wh("whAuth")\n A["Autorisation"] --> C1["POST /captures<br/>tranche 1"]:::call\n C1 --> C2["POST /captures<br/>tranche 2…"]:::call\n C2 --> Z["POST /cancels<br/>clôturer le solde"]:::call\n Z --> ZF["Clôturée"]\n click C1 call pay("cap40","POST","/payments/{ref}/captures")\n click C2 call pay("cap40","POST","/payments/{ref}/captures")\n click Z call pay("cancel","POST","/payments/{ref}/cancels")'},
   {h:'Avec token · capture multiple OFF',axes:[['MANUAL','on'],['token','on'],['multi-capture OFF','acc']],
    why:"Une seule capture possible : elle clôture l'autorisation. Pour encaisser le reste, tu ré-autorises le solde sur le token.",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Autorisation"]\n click q0 call pay("sessionManual","POST","/sessions")\n click q2 wh("whAuth")\n A["Autorisation"] --> C["POST /captures<br/>partielle"]:::call\n C --> X["Clôturée"]\n X --> R["POST /payments<br/>reste sur token"]:::call\n click C call pay("cap40","POST","/payments/{ref}/captures")\n click R call pay("reste6","POST","/payments")'},
   {h:'Sans token · capture multiple OFF',axes:[['MANUAL','on'],['sans token',''],['multi-capture OFF','acc']],
    why:"Le pire cas : une capture partielle clôture l'autorisation et le solde non capturé est définitivement perdu (ni 2ᵉ capture, ni ré-auth sans token).",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Autorisation"]\n click q0 call pay("sessionManual","POST","/sessions")\n click q2 wh("whAuth")\n A["Autorisation"] --> C["POST /captures<br/>partielle"]:::call\n C --> X["Clôturée<br/>reste perdu"]\n click C call pay("cap40","POST","/payments/{ref}/captures")',
    warn:"À éviter si un reliquat est probable."}
 ]},
 {tag:'#2566',title:'Clôture / Annulation',flow:'ECOM',lead:"Libérer la partie non capturée d'une autorisation. Pré-aut comme finale. Appel /cancels.",schemas:[
   {h:'Sans capture (avec ou sans token)',axes:[['MANUAL','on']],
    why:"Tu renonces au paiement avant tout encaissement : l'autorisation est annulée et les fonds du client sont libérés.",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Autorisation"]\n click q0 call pay("sessionManual","POST","/sessions")\n click q2 wh("whAuth")\n A["Autorisation"] --> D["POST /cancels<br/>clôture totale"]:::call\n D -->|OK| Z["Clôturée / annulée"]\n D -->|KO| E["Toujours en cours"]\n click D call pay("cancel","POST","/payments/{ref}/cancels")'},
   {h:'Avec capture partielle',axes:[['MANUAL','on']],
    why:"Tu as encaissé une partie et tu libères le reste : seule la part non capturée est annulée ; le montant déjà capturé reste dû (et pourra être remboursé).",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> A["Autorisation"]\n click q0 call pay("sessionManual","POST","/sessions")\n click q2 wh("whAuth")\n A["Autorisation"] --> C["POST /captures<br/>partielle"]:::call\n C --> D["POST /cancels<br/>clôture du restant"]:::call\n D --> Z["Partiellement clôturée"]\n click C call pay("cap40","POST","/payments/{ref}/captures")\n click D call pay("cancel","POST","/payments/{ref}/cancels")',
    info:"La clôture n'annule que la part <b>non capturée</b>."}
 ]},
 {tag:'#2567',title:'Remboursement',flow:'ECOM',lead:"Rendre tout ou partie d'un montant déjà capturé. Appel /refunds (montant obligatoire).",schemas:[
   {h:'Remboursement total',axes:[['capturé','on']],
    why:"Le paiement est capturé et tu rends tout au client, en un appel.",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> q3["POST /captures"]:::call\n q3 --> q4["webhook<br/>CAPTURE"]:::hook\n q4 --> A["Capturé"]\n click q0 call pay("session","POST","/sessions")\n click q3 call pay("capTotal","POST","/payments/{ref}/captures")\n click q2 wh("whAuth")\n click q4 wh("whCapture")\n A["Capturé"] --> R["POST /refunds<br/>total"]:::call\n R -->|OK| Z["Remboursé"]\n R -->|KO| E["Reste capturé"]\n click R call pay("refundTotal","POST","/payments/{ref}/refunds")'},
   {h:'Remboursement partiel (en plusieurs fois)',axes:[['capturé','on']],
    why:"Tu rembourses par morceaux ; tant que la somme cumulée ne dépasse pas le capturé, ça passe. Un remboursement qui ferait dépasser le total capturé est refusé.",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : le client<br/>saisit sa carte"]:::client\n q1 --> q2["webhook<br/>AUTHORISATION"]:::hook\n q2 --> q3["POST /captures"]:::call\n q3 --> q4["webhook<br/>CAPTURE"]:::hook\n q4 --> A["Capturé 100,00"]\n click q0 call pay("session","POST","/sessions")\n click q3 call pay("capTotal","POST","/payments/{ref}/captures")\n click q2 wh("whAuth")\n click q4 wh("whCapture")\n A["Capturé 100,00"] --> R1["POST /refunds<br/>tranche 1"]:::call\n R1 --> R2["POST /refunds<br/>tranche 2…"]:::call\n R2 --> T["Total remboursé"]\n R1 -->|dépasserait| KO["Refusé"]\n click R1 call pay("refund30","POST","/payments/{ref}/refunds")\n click R2 call pay("refund30","POST","/payments/{ref}/refunds")',
    warn:"Un remboursement dont la somme cumulée dépasse le capturé est refusé."}
 ]},
 {tag:'#2548',title:'Tokenisation simple',flow:'ECOM → ContAuth',lead:"Enregistrer un moyen de paiement sans débiter (session à montant 0), pour l'utiliser plus tard.",schemas:[
   {h:'Tokeniser puis réutiliser',axes:[['montant 0','on'],['token','on']],
    why:"Tu enregistres la carte du client sans rien débiter (session à 0). Le token obtenu peut ensuite être révoqué, ou servir à autoriser un paiement plus tard (initié marchand).",
    d:'flowchart LR\n S["POST /sessions<br/>0 € + token"]:::call --> DI["Drop-in : le client<br/>saisit sa carte"]:::client\n DI --> WT["webhook<br/>token reçu"]:::hook\n WT --> Tok["Carte enregistrée<br/>rien débité"]\n Tok --> R["DELETE<br/>/stored-payment-methods"]:::call\n Tok --> Uu["POST /payments<br/>utiliser (MIT)"]:::call\n click S call pay("tokenise","POST","/sessions")\n click WT wh("whToken")\n click R call pay("","DELETE","/stored-payment-methods/{token}")\n click Uu call pay("mit10","POST","/payments")'}
 ]},
 {tag:'#2822',title:'Annulation d\'order (ANCV + CB)',flow:'ECOM',lead:"Défaire un paiement composite (plusieurs moyens sur un même achat) en inversant chaque jambe. Appel /orders/{orderPspReference}/reversals.",schemas:[
   {h:'Order composite ANCV + carte',axes:[['ANCV + carte','on'],['1 seul appel','on']],
    why:"Un achat payé 40 € en ANCV + 60 € en carte forme un « order ». On ne peut pas appeler le /orders/cancel natif d\'Adyen (il exige un orderData jamais visible via le Drop-in, périmètre PCI) : un seul appel retrouve les deux jambes et les inverse chacune. La carte revient toujours ; la jambe ANCV seulement dans les 4h.",
    d:'flowchart LR\n q0["POST /sessions"]:::call --> q1["Drop-in : ANCV + carte"]:::client\n q1 --> A["webhook<br/>ORDER_CLOSED"]:::hook\n click q0 call pay("session","POST","/sessions")\n click A wh("whOrderClosed")\n A --> G["GET /orders/{ref}<br/>consulter les jambes"]:::call\n click G call pay("","GET","/orders/{orderPspReference}")\n A --> R["POST /orders/{ref}<br/>/reversals"]:::call\n R --> RES["Résolution<br/>des 2 jambes"]\n RES --> CB["Jambe carte<br/>reversée"]\n RES --> AN{"Jambe ANCV<br/>dans les 4h ?"}\n AN -->|oui| K1["ANCV reversée"]\n AN -->|non| K2["ANCV refusée"]\n CB --> S["Réponse par jambe<br/>+ status"]\n K1 --> S\n K2 --> S\n click R call pay("cancel","POST","/orders/{orderPspReference}/reversals")',
    warn:"Jambe ANCV hors des 4h → elle ressort <b>REFUSED</b> pendant que la carte est bien inversée : <code class=\'inl\'>status</code> global = <b>PARTIAL</b>. Rejouable avec la même Idempotency-Key.",
    info:"<code class=\'inl\'>GET /orders/{orderPspReference}</code> liste les jambes de l'order (pspReference + moyen de paiement) pour réconciliation, sans rien inverser. <code class=\'inl\'>status</code> : RECEIVED (toutes) · PARTIAL (mélange) · FAILED (toutes en échec). Chaque jambe porte son <code class=\'inl\'>outcome</code> (RECEIVED / REFUSED / UNAVAILABLE)."}
 ]},
 {tag:'#2742',title:'Paiement sur terminal (TPE)',flow:'POS',lead:"Encaisser sur un terminal physique via l'API Terminal (nexo). Asynchrone : on déclenche, le client paie sur le boîtier, l'issue revient par statut et/ou webhook.",schemas:[
   {h:'Paiement TPE simple',axes:[['POS','on'],['async','acc']],
    why:"Tu récupères la liste des terminaux du store pour choisir le boîtier, puis tu déclenches le paiement : le TPE affiche le montant, le client paie. La réponse immédiate est <b>IN_PROGRESS</b> ; l'issue définitive arrive par <b>webhook</b> et/ou en interrogeant le statut.",
    d:'flowchart LR\n T["GET /stores/{id}<br/>/terminals"]:::call --> P["POST /payments/pos<br/>202 IN_PROGRESS"]:::call\n P --> C["Client paie<br/>sur le TPE"]:::client\n C --> W["webhook<br/>AUTHORISATION"]:::hook\n W --> OK["Approuvé"]\n C --> G["GET /payments/pos<br/>/{serviceId}"]:::call\n G --> OK\n click T call pay("","GET","/stores/{publicStoreId}/terminals")\n click P call pay("posPay","POST","/payments/pos")\n click W wh("whPosAuth")\n click G call pay("","GET","/payments/pos/{serviceId}")',
    info:"<code class='inl'>deviceId</code> = le <b>POIID</b> du terminal (issu de la liste). Le montant est transmis à Adyen en unités <b>majeures</b> (Terminal API nexo)."},
   {h:'Pré-autorisation TPE (caution)',axes:[['POS','on'],['preAuth:true','on'],['MANUAL','on']],
    why:"Empreinte au terminal : tu bloques un montant sans débiter, puis tu captures le montant réel plus tard (ou tu annules). Comme une caution e-commerce, mais sur le boîtier.",
    d:'flowchart LR\n P["POST /payments/pos<br/>preAuth"]:::call --> C["Client valide<br/>sur le TPE"]:::client\n C --> W["webhook<br/>AUTHORISATION"]:::hook\n W --> A["Auth pré-aut (TPE)"]\n A --> CAP["POST /captures"]:::call\n CAP --> WC["webhook<br/>CAPTURE"]:::hook\n WC --> Z["Capturé"]\n click P call pay("posPreauth","POST","/payments/pos")\n click W wh("whPosAuth")\n click CAP call pay("cap40","POST","/payments/{ref}/captures")\n click WC wh("whCapture")',
    info:"La capture et l'annulation se font ensuite via les mêmes endpoints que la carte (<code class='inl'>/captures</code>, <code class='inl'>/cancels</code>)."},
   {h:'Annuler un paiement TPE en cours',axes:[['POS','on'],['abort','acc']],
    why:"Le client renonce ou l'agent se trompe : tant que la transaction n'est pas finie sur le boîtier, tu peux l'abandonner. Si elle est déjà passée, c'est un remboursement / une annulation classique.",
    d:'flowchart LR\n P["POST /payments/pos<br/>202 IN_PROGRESS"]:::call --> C["Transaction en cours<br/>sur le TPE"]:::client\n C --> AB["POST /payments/pos<br/>/{serviceId}/abort"]:::call\n AB --> Z["Annulé"]\n click P call pay("posPay","POST","/payments/pos")\n click AB call pay("","POST","/payments/pos/{serviceId}/abort")'}
 ]}
];
